project:
  type: website

website:
  title: "Analyse des données"

  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: manipulationR.qmd
        text: Manipulation
      - href: Gestion_de_NA.qmd
        text: Gestion des NA
      - href: visualisation.qmd
        text: Visualisation
      - href: exerciceR.qmd
        text: Exercice Manipulation
      - href: exercice_NA.qmd
        text: Exercice NA
      - href: exercice_Viz.qmd
        text: Exercice Visualisation
      - about.qmd
      
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
