---
title: "Analyse des données"
---
<p id=textIntro>Bienvenue sur notre plateforme de cours sur l'analyse de données. Ce site vous offre des ressources pour apprendre la manipulation et la visualisation des donnée en R.
.</p>

### Introduction à la manipulation avancée des données en R

<p id=textIntro>Ce cours est conçu pour vous offrir une compréhension approfondie des techniques essentielles en <strong>R</strong>. Nous aborderons la manipulation des chaînes de caractères, la gestion des valeurs manquantes (NA), la manipulation avancée des dates et des séries chronologiques, ainsi que la visualisation des données avec `ggplot2`.

<strong>Vous apprendrez comment utiliser les puissantes librairies de R telles que `lubridate` pour les dates et `xts` pour les séries chronologiques, facilitant ainsi le traitement et l’analyse de données complexes</strong><br>. Ce cours utilisera également le jeu de données `mtcars` pour illustrer comment créer des graphiques expressifs et informatifs.</p>

<p id=textIntro>Bonjour ! Moi c'est <strong>Joseph Midiburo</strong>, Etudiant à l'IA School pour plus d'infos me concernant voici mon Linkedin <a href="https://www.linkedin.com/in/joseph-midiburo-a58022222/">Joseph MIDIBURO</a>Amusez vous bien</a> <a href=manipulationR.qmd>Manipulation des données R</a><a href=Gestion_de_NA.qmd>Gestion des NA</a><a href=visualisation.qmd>Visualisation des données R</a><a href=exerciceR.qmd>Exercices Manipulation</a><a href=exercice_NA.qmd>Exercice NA</a><a href=exercice_Viz.qmd>Exercice Visualisation</a></p>